apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-postgres
  template:
    metadata:
      labels:
        app: immich-postgres
    spec:
      containers:
      - name: postgres
        image: tensorchord/pgvecto-rs:pg16-v0.2.1 # Official image recommended by Immich
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: immich-secret
              key: DB_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: immich-secret
              key: DB_PASSWORD
        - name: POSTGRES_DB
          value: "immich"
        volumeMounts:
        - name: immich-postgres-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres-data
      volumes:
      - name: immich-postgres-data
        persistentVolumeClaim:
          claimName: immich-db-pvc
     