---
apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tailscale
  namespace: tailscale # Place the source in the same namespace
spec:
  interval: 15m
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 15m
  chart:
    spec:
      chart: tailscale-operator
      version: "1.68.0" # Optional: Pin to a specific chart version for stability
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    operator:
      apiSecret:
        secretName: "tailscale-auth"
        secretKey: "authkey"
    clusterName: "homelab-nas"

    # Configuration for the proxy that exposes services.
    # Set 'mode: false' if your cluster nodes can directly listen on host ports.
    # Set 'mode: true' (default) to run the proxy as a separate Deployment.
    # For most cloud providers or CNI configurations, 'true' is the safer choice.
    apiServerProxy:
      mode: true
