apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-secret-from-vault
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: immich-secret 
    creationPolicy: Owner
  data:
  - secretKey: DB_PASSWORD 
    remoteRef:
      key: secret/immich      
      property: DB_PASSWORD   
  - secretKey: DB_USERNAME 
    remoteRef:
      key: secret/immich     
      property: DB_USERNAME  