apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - argocd-application.yaml
  - external-secret.yaml
  - ingress.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - pvc.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - server-deployment.yaml
  - service.yaml
  - vault-secret-store.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: immich
