apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    vault:
      server: "http://vault.vault:8200"
      path: "secret" 
      version: "v2" 
      auth:
        # Authenticate using the Kubernetes Service Account method
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccount:
            name: "external-secrets"
            namespace: "external-secrets"