apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  # Replace this with a range of unused IPs from your LAN!
  addresses:
  - 192.168.0.210-192.168.0.220
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: homelab-lb
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
