apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-app-nginx-ingress
  namespace: nginx
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
      - nginx-app-2
  rules:
  - host: "nginx-app-2"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
