apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd # This application CRD lives in the 'argocd' namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  # --- Source: Where the Helm chart lives ---
  source:
    repoURL: https://pkgs.tailscale.com/helmcharts
    chart: tailscale-operator
    targetRevision: "1.88.2" # Good practice to pin the chart version

    # --- Helm Values: How to configure the operator ---
    helm:
      values: |
    
        # Use the same name as your Talos cluster for consistency!
        clusterName: "homelab-nas"

        # Configuration for the proxy that exposes services
        apiServerProxy:
          mode: true
        funnel:
          mode: true
          oauth:
            secretName: "tailscale-funnel-creds"

  # --- Destination: Where to deploy the resources ---
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale # Deploy the operator into the 'tailscale' namespace

  # --- Sync Policy: How Argo CD should keep it in sync ---
  syncPolicy:
    automated:
      prune: true    # Delete resources that are no longer in the Helm chart
      selfHeal: true # Automatically sync if the live state drifts from Git
    syncOptions:
      - CreateNamespace=true # Automatically create the 'tailscale' namespace if it doesn't exist
