apiVersion: batch/v1
kind: Job
metadata:
  name: vault-store-secrets
  namespace: vault
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    metadata:
      name: vault-store-secrets
    spec:
      restartPolicy: OnFailure
      containers:
        - name: vault-store-secrets
          image: hashicorp/vault:1.15.6
          command:
            - /bin/sh
            - -c
            - |
              set -e
              
              export VAULT_ADDR='http://vault.vault.svc.cluster.local:8200'
              export VAULT_TOKEN='root'
              
              # Wait for Vault to be ready
              echo "Waiting for Vault to be ready..."
              until vault status >/dev/null 2>&1; do
                echo "Vault not ready yet, waiting..."
                sleep 2
              done
              
              echo "Storing secrets in Vault..."
              
              # Store Immich database password
              # CHANGE THIS PASSWORD to your actual secure password
              vault kv put secret/immich \
                DB_PASSWORD="YOUR_SUPER_SECRET_PASSWORD"
              
              # Add more secrets for other applications as needed
              # vault kv put secret/myapp \
              #   API_KEY="your-api-key" \
              #   SECRET_TOKEN="your-secret-token"
              
              echo "Secrets stored successfully!"

