apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  # Source - Custom ArgoCD configurations from Git
  source:
    repoURL: 'https://github.com/marcellof23/cellotadel.git'
    targetRevision: HEAD
    path: argocd/config
    kustomize: {}

  # Destination
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

