# argocd-apps/metallb-operator-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd # All Argo CD apps live in the 'argocd' namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/marcellof23/cellotadel.git'
    targetRevision: HEAD
    path: argocd/apps/metallb # <-- Path to the installer manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
