apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  # Source of the application - External Secrets Helm chart
  source:
    repoURL: 'https://charts.external-secrets.io'
    targetRevision: 0.10.5  # External Secrets chart version
    chart: external-secrets
    helm:
      values: |
        installCRDs: true
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 200m

  # Destination cluster and namespace
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

